class ApplicationController < ActionController::API

    #CSRF token generated by the system, checks to make sure the user is a real user in api its different. 
    skip_before_action :verify_authenticity_token 
end
